# basic option
  title: REEL
  author: REEL Master
  email: reelmaster@gmail.com
  dscription: A lovely wonderful blog
  twitter_username: reelmaster
  github_username: reelmaster
  
# Build settings

markdown: kramdown
theme: minima
